# Setup
setup: multi_task

# Database
train_db_name: RCCContext
val_db_name: RCCContext
trBatch: 8
valBatch: 8
nworkers: 4

# Optimizer and scheduler
epochs: 100
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
scheduler: poly

# Model
model: mti_net 
backbone: hrnet_w18
backbone_kwargs:
   pretrained: False
   dilated: False
head: hrnet

# Tasks
task_dictionary:
   include_classify: True
   include_SSL: True
   edge_w: 0.95

auxilary_task_dictionary:
   include_classify: True
   include_SSL: True
   edge_w: 0.95 # Copy of task dictionary

# Loss kwargs
loss_kwargs:
   loss_scheme: mti_net
   loss_weights:
       classify: 2.0
       SSL: 1.0

# Eval only final 10 epochs for speed-up
eval_final_10_epochs_only: True
